### ISSUE TITLE
Enabling TOTP break desktop client

### ISSUE THREAD

**Issue by rmrfslashbin** [ChristophWurst/twofactor_totp#59] opened 2016-09-22 14:11 UTC
After enabling TOTP for a user account, the Linux desktop client is not able to login. Disabling TOTP resolved login issue.

**Comment by ChristophWurst** [comment] 2016-09-23 07:20
Duplicate of https://github.com/ChristophWurst/twofactor_totp/issues/55 and not a bug, but a security feature ;-)

**Closed by ChristophWurst** 2016-09-23 07:20 UTC
