### ISSUE TITLE
QR code invalid since v0.4.0

### ISSUE THREAD

**Issue by GSquad934** [ChristophWurst/twofactor_totp#39] opened 2016-08-21 15:05 UTC
Hello,

Since the last update to version 0.4.0, all new created QR codes are invalid (the key itself works well though). This error occurs with multiple authenticator applications and on multiple devices. If I encode the key manually, it works just fine.

![error_qrcode](https://cloud.githubusercontent.com/assets/21157595/17837972/39bf7bc0-67c1-11e6-8bca-370eadd641e1.png)

I'm using ownCloud 9.1. I already tried to do the following:

- Uninstall/Reinstall the app
- Use it on another ownCloud instance
- Disable/Enable 2FA for that specific user
- Test with multiple users

Thanks.
Regards.

Gaétan

**Comment by ChristophWurst** [comment] 2016-08-22 08:52
Hi,
this is a duplicate of #37

**Closed by ChristophWurst** 2016-08-22 08:52 UTC

**Comment by ChristophWurst** [comment] 2016-08-25 12:59
@GSquad934 please test https://github.com/ChristophWurst/twofactor_totp/releases/tag/0.4.1 and tell me if the issue is solved for you, too. Thanks ;-)

**Comment by GSquad934** [comment] 2016-08-25 13:51
Hi there, it works well and the issue is fixed.

Thank you ;-)
Regards,

Gaétan
