### ISSUE TITLE
/login/challenge/totp reloading every 5 sec

### ISSUE THREAD

**Issue by jaylik** [ChristophWurst/twofactor_totp#24] opened 2016-07-26 08:10 UTC
Don't know if this is Owncloud or plugin issue but page is refreshed every 5 sec and its hard to type the token with mobile devices.

**Comment by tribut** [comment] 2016-07-26 09:02
Duplicate of #19

**Closed** 2016-07-26 17:13 UTC

**Comment by ChristophWurst** [comment] 2016-08-22 08:23
This was fixed for Nextcloud 11 and Nextcloud 10, see https://github.com/nextcloud/server/pull/984
